CREATE TABLE day_values (
    id SERIAL PRIMARY KEY,
    value_id INTEGER NOT NULL REFERENCES habit_values(id) ON DELETE CASCADE,
    user_day_id INTEGER NOT NULL REFERENCES user_days(id) ON DELETE CASCADE,
    text VARCHAR,
    number INTEGER,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);
